'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class AppointmentForm

	''' <summary>
	''' lblSubject control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblSubject As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' tbSubject control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected tbSubject As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

	''' <summary>
	''' lblLocation control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblLocation As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' tbLocation control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected tbLocation As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

	''' <summary>
	''' lblLabel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblLabel As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' edtLabel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected edtLabel As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' lblStartDate control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblStartDate As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' edtStartDate control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected edtStartDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

	''' <summary>
	''' lblEndDate control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblEndDate As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' edtEndDate control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected edtEndDate As Global.DevExpress.Web.ASPxEditors.ASPxDateEdit

	''' <summary>
	''' lblStatus control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblStatus As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' edtStatus control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected edtStatus As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' chkAllDay control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected chkAllDay As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' lblAllDay control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblAllDay As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' lblResource control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblResource As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' ddResource control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ddResource As Global.DevExpress.Web.ASPxEditors.ASPxDropDownEdit

	''' <summary>
	''' edtResource control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected edtResource As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' chkReminder control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected chkReminder As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' lblReminder control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblReminder As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' cbReminder control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected cbReminder As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' tbDescription control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected tbDescription As Global.DevExpress.Web.ASPxEditors.ASPxMemo

	''' <summary>
	''' AppointmentRecurrenceForm1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected AppointmentRecurrenceForm1 As Global.DevExpress.Web.ASPxScheduler.Controls.AppointmentRecurrenceForm

	''' <summary>
	''' btnOk control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnOk As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnCancel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnCancel As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnDelete control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnDelete As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' schedulerStatusInfo control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected schedulerStatusInfo As Global.DevExpress.Web.ASPxScheduler.Controls.ASPxSchedulerStatusInfo
End Class
