'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class AppointmentFormEx

    ''' <summary>
    ''' lblSubject control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblSubject As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' tbSubject control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected tbSubject As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' lblLocation control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblLocation As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' tbLocation control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected tbLocation As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' lblLabel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblLabel As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' edtLabel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected edtLabel As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' lblStartDate control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblStartDate As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' edtStartDate control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected edtStartDate As Global.DevExpress.Web.ASPxDateEdit

    ''' <summary>
    ''' lblEndDate control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblEndDate As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' edtEndDate control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected edtEndDate As Global.DevExpress.Web.ASPxDateEdit

    ''' <summary>
    ''' lblStatus control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblStatus As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' edtStatus control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected edtStatus As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' chkAllDay control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected chkAllDay As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' lblAllDay control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblAllDay As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' lblResource control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblResource As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' ddResource control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ddResource As Global.DevExpress.Web.ASPxDropDownEdit

    ''' <summary>
    ''' edtResource control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected edtResource As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' chkReminder control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected chkReminder As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' lblReminder control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblReminder As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cbReminder control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cbReminder As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' tbDescription control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected tbDescription As Global.DevExpress.Web.ASPxMemo

    ''' <summary>
    ''' chkRecurrence control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected chkRecurrence As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' RecurrencePanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected RecurrencePanel As Global.DevExpress.Web.ASPxCallbackPanel

    ''' <summary>
    ''' btnOk control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnOk As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnCancel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnCancel As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnDelete control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnDelete As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' schedulerStatusInfo control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected schedulerStatusInfo As Global.DevExpress.Web.ASPxScheduler.Controls.ASPxSchedulerStatusInfo
End Class
