'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class GotoDateForm

    ''' <summary>
    ''' lblDate control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblDate As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' edtDate control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected edtDate As Global.DevExpress.Web.ASPxDateEdit

    ''' <summary>
    ''' lblView control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblView As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cbView control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cbView As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' btnOk control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnOk As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnCancel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnCancel As Global.DevExpress.Web.ASPxButton
End Class
