'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class HorizontalAppointmentTemplate

	''' <summary>
	''' appointmentDiv control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected appointmentDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	''' <summary>
	''' statusContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected statusContainer As Global.System.Web.UI.HtmlControls.HtmlTableCell

	''' <summary>
	''' imgStartContinueArrow control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected imgStartContinueArrow As Global.System.Web.UI.WebControls.Image

	''' <summary>
	''' lblStartContinueText control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblStartContinueText As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' startTimeClockContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected startTimeClockContainer As Global.System.Web.UI.HtmlControls.HtmlTableCell

	''' <summary>
	''' lblStartTime control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblStartTime As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' imageContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected imageContainer As Global.System.Web.UI.HtmlControls.HtmlTable

	''' <summary>
	''' lblTitle control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblTitle As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' endTimeClockContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected endTimeClockContainer As Global.System.Web.UI.HtmlControls.HtmlTableCell

	''' <summary>
	''' lblEndTime control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblEndTime As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' lblEndContinueText control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblEndContinueText As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' imgEndContinueArrow control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected imgEndContinueArrow As Global.System.Web.UI.WebControls.Image
End Class
