'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class RecurrentAppointmentDeleteForm

    ''' <summary>
    ''' imgWarning control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected imgWarning As Global.DevExpress.Web.ASPxImage

    ''' <summary>
    ''' lblConfirm control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblConfirm As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' rbAction control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rbAction As Global.DevExpress.Web.ASPxRadioButtonList

    ''' <summary>
    ''' btnOk control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnOk As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnCancel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnCancel As Global.DevExpress.Web.ASPxButton
End Class
