'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class ReminderForm

	''' <summary>
	''' lbItems control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lbItems As Global.DevExpress.Web.ASPxEditors.ASPxListBox

	''' <summary>
	''' btnDismissAll control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnDismissAll As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnDismiss control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnDismiss As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' lblClickSnooze control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblClickSnooze As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' cbSnooze control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected cbSnooze As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' btnSnooze control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnSnooze As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
