'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class VerticalAppointmentTemplate

	''' <summary>
	''' appointmentDiv control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected appointmentDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	''' <summary>
	''' statusContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected statusContainer As Global.System.Web.UI.HtmlControls.HtmlTableCell

	''' <summary>
	''' imageContainer control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected imageContainer As Global.System.Web.UI.HtmlControls.HtmlTable

	''' <summary>
	''' lblStartTime control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblStartTime As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' lblEndTime control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblEndTime As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' lblTitle control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblTitle As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' horizontalSeparator control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected horizontalSeparator As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	''' <summary>
	''' lblDescription control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblDescription As Global.DevExpress.Web.ASPxEditors.ASPxLabel
End Class
