'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class ImagePropertiesForm

	''' <summary>
	''' lblSize control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblSize As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' cmbSize control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected cmbSize As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' lblWidth control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblWidth As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' spnWidth control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected spnWidth As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

	''' <summary>
	''' lblPixelWidth control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblPixelWidth As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' lblHeight control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblHeight As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' spnHeight control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected spnHeight As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit

	''' <summary>
	''' lblPixelHeight control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblPixelHeight As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' cellContarainTop control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected cellContarainTop As Global.System.Web.UI.HtmlControls.HtmlTableCell

	''' <summary>
	''' cellContarainSwitcher control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected cellContarainSwitcher As Global.System.Web.UI.HtmlControls.HtmlTableCell

	''' <summary>
	''' cellContarainBottom control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected cellContarainBottom As Global.System.Web.UI.HtmlControls.HtmlTableCell

	''' <summary>
	''' ckbCreateThumbnail control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ckbCreateThumbnail As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' lblThumbnailFileName control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblThumbnailFileName As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' txbThumbnailFileName control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected txbThumbnailFileName As Global.DevExpress.Web.ASPxEditors.ASPxTextBox

	''' <summary>
	''' lblImagePosition control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblImagePosition As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' cmbImagePosition control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected cmbImagePosition As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

	''' <summary>
	''' ckbWrapTextArroundImage control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ckbWrapTextArroundImage As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' lblImageDescription control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblImageDescription As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' txbDescription control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected txbDescription As Global.DevExpress.Web.ASPxEditors.ASPxTextBox
End Class
