'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class InsertTableForm

    ''' <summary>
    ''' MainPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected MainPanel As Global.DevExpress.Web.ASPxPanel

    ''' <summary>
    ''' PanelContent1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PanelContent1 As Global.DevExpress.Web.PanelContent

    ''' <summary>
    ''' rpSize control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpSize As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' HtmlEditorRoundPanelContent1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HtmlEditorRoundPanelContent1 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    ''' <summary>
    ''' lblSize control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblSize As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' lblColumns control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblColumns As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' spnColumns control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected spnColumns As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' lblRows control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblRows As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' spnRows control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected spnRows As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' lblWidth control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblWidth As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cmbWidth control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbWidth As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' txbWidth control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbWidth As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' cmbWidthType control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbWidthType As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' ckbColumnsEqualWidth control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ckbColumnsEqualWidth As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' lblHeight control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblHeight As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cmbHeight control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbHeight As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' txbHeight control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbHeight As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' cmbHeightType control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbHeightType As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' rpLayout control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpLayout As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' HtmlEditorRoundPanelContent4 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HtmlEditorRoundPanelContent4 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    ''' <summary>
    ''' lblLayout control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblLayout As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' lblPadding control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblPadding As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' spnPadding control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected spnPadding As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' lblAlign control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblAlign As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cmbAlign control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbAlign As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' lblSpacing control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblSpacing As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' spnSpacing control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected spnSpacing As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' rpAppearance control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpAppearance As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' HtmlEditorRoundPanelContent3 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HtmlEditorRoundPanelContent3 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    ''' <summary>
    ''' lblAppearance control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblAppearance As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' lblBorderColor control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblBorderColor As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbBorderColor control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbBorderColor As Global.DevExpress.Web.ASPxColorEdit

    ''' <summary>
    ''' lblBorderSize control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblBorderSize As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' spnBorderSize control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected spnBorderSize As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' lblBackgroundColor control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblBackgroundColor As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbBackgroundColor control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbBackgroundColor As Global.DevExpress.Web.ASPxColorEdit

    ''' <summary>
    ''' ckbAccessibility control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ckbAccessibility As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' rpAccessibility control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpAccessibility As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' HtmlEditorRoundPanelContent2 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HtmlEditorRoundPanelContent2 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    ''' <summary>
    ''' lblHeaders control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblHeaders As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cmbHeaders control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbHeaders As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' lblCaption control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblCaption As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbCaption control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbCaption As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' lblSummary control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblSummary As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbSummary control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbSummary As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' btnOk control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnOk As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnCancel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnCancel As Global.DevExpress.Web.ASPxButton
End Class
