'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class InsertImageForm

    ''' <summary>
    ''' Panel1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected Panel1 As Global.DevExpress.Web.ASPxPanel

    ''' <summary>
    ''' rblFromTheWeb control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rblFromTheWeb As Global.DevExpress.Web.ASPxRadioButton

    ''' <summary>
    ''' rblFromThisComputer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rblFromThisComputer As Global.DevExpress.Web.ASPxRadioButton

    ''' <summary>
    ''' rpInsertImage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpInsertImage As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' lblImageUrl control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblImageUrl As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbInsertImageUrl control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbInsertImageUrl As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' ckbSaveToServer control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ckbSaveToServer As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' lblBrowse control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblBrowse As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' uplImage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected uplImage As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorUploadControl

    ''' <summary>
    ''' ucImagePropertiesForm control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ucImagePropertiesForm As Global.ImagePropertiesForm

    ''' <summary>
    ''' ckbMoreImageOptions control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ckbMoreImageOptions As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' btnInsertImage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnInsertImage As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnChangeImage control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnChangeImage As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnInsertImageCancel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnInsertImageCancel As Global.DevExpress.Web.ASPxButton
End Class
