'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class InsertLinkFrom

    ''' <summary>
    ''' MainPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected MainPanel As Global.DevExpress.Web.ASPxPanel

    ''' <summary>
    ''' rblLinkType control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rblLinkType As Global.DevExpress.Web.ASPxRadioButtonList

    ''' <summary>
    ''' rpInsertLink control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpInsertLink As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' lblUrl control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblUrl As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbURL control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbURL As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' lblEmailTo control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblEmailTo As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbEmailTo control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbEmailTo As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' lblSubject control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblSubject As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbSubject control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbSubject As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' lblLinkDisplay control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblLinkDisplay As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' lblText control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblText As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbText control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbText As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' lblToolTip control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblToolTip As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbToolTip control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbToolTip As Global.DevExpress.Web.ASPxTextBox

    ''' <summary>
    ''' ckbOpenInNewWindow control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ckbOpenInNewWindow As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' btnOk control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnOk As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnChange control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnChange As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnCancel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnCancel As Global.DevExpress.Web.ASPxButton
End Class
