'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------




Imports Microsoft.VisualBasic
Imports System
Partial Public Class PasteFromWordForm

	''' <summary>
	''' lblB141214 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblB141214 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' MainPanel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected MainPanel As Global.DevExpress.Web.ASPxPanel.ASPxPanel

	''' <summary>
	''' PanelContent1 control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected PanelContent1 As Global.DevExpress.Web.ASPxPanel.PanelContent

	''' <summary>
	''' lblDescription control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected lblDescription As Global.DevExpress.Web.ASPxEditors.ASPxLabel

	''' <summary>
	''' ckbStripFont control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected ckbStripFont As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

	''' <summary>
	''' btnOk control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnOk As Global.DevExpress.Web.ASPxEditors.ASPxButton

	''' <summary>
	''' btnCancel control.
	''' </summary>
	''' <remarks>
	''' Auto-generated field.
	''' To modify move field declaration from designer file to code-behind file.
	''' </remarks>
	Protected btnCancel As Global.DevExpress.Web.ASPxEditors.ASPxButton
End Class
