'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class TableColumnPropertiesForm

    ''' <summary>
    ''' MainPanel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected MainPanel As Global.DevExpress.Web.ASPxPanel

    ''' <summary>
    ''' PanelContent1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected PanelContent1 As Global.DevExpress.Web.PanelContent

    ''' <summary>
    ''' rpSize control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpSize As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' HtmlEditorRoundPanelContent1 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HtmlEditorRoundPanelContent1 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    ''' <summary>
    ''' lblSize control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblSize As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' lblWidth control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblWidth As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cmbWidth control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbWidth As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' txbWidth control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbWidth As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' cmbWidthType control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbWidthType As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' lblHeight control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblHeight As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cmbHeight control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbHeight As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' txbHeight control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbHeight As Global.DevExpress.Web.ASPxSpinEdit

    ''' <summary>
    ''' cmbHeightType control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbHeightType As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' rpLayout control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpLayout As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' HtmlEditorRoundPanelContent4 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HtmlEditorRoundPanelContent4 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    ''' <summary>
    ''' lblAlign control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblAlign As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' lblHorizontalAlign control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblHorizontalAlign As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cmbAlign control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbAlign As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' lblVerticalAlign control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblVerticalAlign As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' cmbVAlign control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected cmbVAlign As Global.DevExpress.Web.ASPxComboBox

    ''' <summary>
    ''' rpAppearance control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected rpAppearance As Global.DevExpress.Web.ASPxHtmlEditor.ASPxHtmlEditorRoundPanel

    ''' <summary>
    ''' HtmlEditorRoundPanelContent3 control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected HtmlEditorRoundPanelContent3 As Global.DevExpress.Web.ASPxHtmlEditor.HtmlEditorRoundPanelContent

    ''' <summary>
    ''' lblAppearance control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblAppearance As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' lblBackgroundColor control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblBackgroundColor As Global.DevExpress.Web.ASPxLabel

    ''' <summary>
    ''' txbBackgroundColor control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected txbBackgroundColor As Global.DevExpress.Web.ASPxColorEdit

    ''' <summary>
    ''' ckbApplyForAllElements control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected ckbApplyForAllElements As Global.DevExpress.Web.ASPxCheckBox

    ''' <summary>
    ''' btnChange control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnChange As Global.DevExpress.Web.ASPxButton

    ''' <summary>
    ''' btnCancel control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected btnCancel As Global.DevExpress.Web.ASPxButton
End Class
